<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            [
                'author_id' => 1,
                'title' => 'Cien años de soledad',
                'open_library_cover_key' => 'OL37050600M',
                'first_publish_year' => 1967,
                'units_available' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'title' => 'El amor en los tiempos del cólera',
                'open_library_cover_key' => 'OL9134511M',
                'first_publish_year' => 1985,
                'units_available' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'title' => 'Crónica de una muerte anunciada',
                'open_library_cover_key' => 'OL24945433M',
                'first_publish_year' => 1980,
                'units_available' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'title' => 'El coronel no tiene quien le escriba',
                'open_library_cover_key' => 'OL22291514M',
                'first_publish_year' => 1961,
                'units_available' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'title' => 'El general en su laberinto',
                'open_library_cover_key' => 'OL9130999M',
                'first_publish_year' => 1989,
                'units_available' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'title' => 'Relato de un náufrago',
                'open_library_cover_key' => 'OL22938390M',
                'first_publish_year' => 1970,
                'units_available' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'title' => 'Doce cuentos peregrinos',
                'open_library_cover_key' => 'OL25882732M',
                'first_publish_year' => 1992,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'title' => 'Del amor y otros demonios',
                'open_library_cover_key' => 'OL835720M',
                'first_publish_year' => 1994,
                'units_available' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'title' => 'Otoño Del Patriarca',
                'open_library_cover_key' => 'OL9894821M',
                'first_publish_year' => 1973,
                'units_available' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 1,
                'title' => 'La mala hora',
                'open_library_cover_key' => 'OL21323281M',
                'first_publish_year' => 1962,
                'units_available' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 2,
                'title' => 'Das Schloß',
                'open_library_cover_key' => 'OL7461641M',
                'first_publish_year' => 1926,
                'units_available' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 2,
                'title' => 'Die Verwandlung',
                'open_library_cover_key' => 'OL26965562M',
                'first_publish_year' => 1915,
                'units_available' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 2,
                'title' => 'Der Proceß',
                'open_library_cover_key' => 'OL9019142M',
                'first_publish_year' => 1825,
                'units_available' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 2,
                'title' => 'Amerika',
                'open_library_cover_key' => 'OL12399571M',
                'first_publish_year' => 1927,
                'units_available' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 2,
                'title' => 'Briefe an Milena',
                'open_library_cover_key' => 'OL2056537M',
                'first_publish_year' => 1952,
                'units_available' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 2,
                'title' => 'Short stories',
                'open_library_cover_key' => 'OL3071897M',
                'first_publish_year' => 1946,
                'units_available' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 2,
                'title' => 'Brief an den Vater',
                'open_library_cover_key' => 'OL12680294M',
                'first_publish_year' => 1953,
                'units_available' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 2,
                'title' => 'The diaries of Franz Kafka',
                'open_library_cover_key' => 'OL1942972M',
                'first_publish_year' => 1948,
                'units_available' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 2,
                'title' => 'A metamorfose',
                'open_library_cover_key' => 'OL39224511M',
                'first_publish_year' => 2017,
                'units_available' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 2,
                'title' => 'Antología de la literatura fantástica',
                'open_library_cover_key' => 'OL24240650M',
                'first_publish_year' => 1940,
                'units_available' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 3,
                'title' => 'Voyage au Centre de la Terre',
                'open_library_cover_key' => 'OL7027686M',
                'first_publish_year' => 1867,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 3,
                'title' => 'Le Tour du Monde en Quatre-Vingts Jours',
                'open_library_cover_key' => 'OL7050533M',
                'first_publish_year' => 1872,
                'units_available' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 3,
                'title' => 'De la terre à la lune',
                'open_library_cover_key' => 'OL13523352M',
                'first_publish_year' => 1865,
                'units_available' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 3,
                'title' => 'Vingt mille lieues sous les mers',
                'open_library_cover_key' => 'OL24245739M',
                'first_publish_year' => 1870,
                'units_available' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 3,
                'title' => 'L\'Île mystérieuse',
                'open_library_cover_key' => 'OL9868901M',
                'first_publish_year' => 1870,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 3,
                'title' => 'Around the World in 80 Days',
                'open_library_cover_key' => 'OL28755040M',
                'first_publish_year' => 1988,
                'units_available' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 3,
                'title' => 'Cinq semaines en ballon',
                'open_library_cover_key' => 'OL23288585M',
                'first_publish_year' => 1867,
                'units_available' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 3,
                'title' => 'Michael Strogoff',
                'open_library_cover_key' => 'OL8365111M',
                'first_publish_year' => 1877,
                'units_available' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 3,
                'title' => 'Paris au XXe siècle',
                'open_library_cover_key' => 'OL1232484M',
                'first_publish_year' => 1994,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 3,
                'title' => '20,000 Leagues under The Sea',
                'open_library_cover_key' => 'OL25879477M',
                'first_publish_year' => 1998,
                'units_available' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 4,
                'title' => 'La Chute',
                'open_library_cover_key' => 'OL5942384M',
                'first_publish_year' => 1917,
                'units_available' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 4,
                'title' => 'L’étranger',
                'open_library_cover_key' => 'OL6508147M',
                'first_publish_year' => 1942,
                'units_available' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 4,
                'title' => 'La Peste',
                'open_library_cover_key' => 'OL21317954M',
                'first_publish_year' => 1942,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 4,
                'title' => 'Le mythe de Sisyphe',
                'open_library_cover_key' => 'OL9048629M',
                'first_publish_year' => 1941,
                'units_available' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 4,
                'title' => 'L\'Homme révolté',
                'open_library_cover_key' => 'OL8837456M',
                'first_publish_year' => 1951,
                'units_available' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 4,
                'title' => 'L\'exil et le royaume',
                'open_library_cover_key' => 'OL33013747M',
                'first_publish_year' => 1951,
                'units_available' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 4,
                'title' => 'La Mort heureuse',
                'open_library_cover_key' => 'OL4848659M',
                'first_publish_year' => 1971,
                'units_available' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 4,
                'title' => 'The Myth of Sisyphus and Other Essays',
                'open_library_cover_key' => 'OL1888949M',
                'first_publish_year' => 1955,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 4,
                'title' => 'Le premier homme',
                'open_library_cover_key' => 'OL47862971M',
                'first_publish_year' => 1994,
                'units_available' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 4,
                'title' => 'Plays (Caligula / Malentendu / L\'État de Siège / Justes)',
                'open_library_cover_key' => 'OL32978138M',
                'first_publish_year' => 1958,
                'units_available' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 5,
                'title' => 'Pedro Páramo',
                'open_library_cover_key' => 'OL18434271M',
                'first_publish_year' => 1955,
                'units_available' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 5,
                'title' => 'El llano en llamas',
                'open_library_cover_key' => 'OL12761168M',
                'first_publish_year' => 1953,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 5,
                'title' => 'Pedro Páramo / El llano en llamas',
                'open_library_cover_key' => 'OL9112346M',
                'first_publish_year' => 1969,
                'units_available' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 5,
                'title' => 'Spanish Short Stories 1 — Cuentos hispánicos 1',
                'open_library_cover_key' => 'OL9300648M',
                'first_publish_year' => 1966,
                'units_available' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 5,
                'title' => 'Aires de las colinas',
                'open_library_cover_key' => 'OL18321838M',
                'first_publish_year' => 2000,
                'units_available' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 5,
                'title' => 'El gallo de oro',
                'open_library_cover_key' => 'OL25565787M',
                'first_publish_year' => 1981,
                'units_available' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 5,
                'title' => 'Los mejores relatos latinoamericanos',
                'open_library_cover_key' => 'OL9116551M',
                'first_publish_year' => 1998,
                'units_available' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 5,
                'title' => 'Antología personal',
                'open_library_cover_key' => 'OL1929427M',
                'first_publish_year' => 1978,
                'units_available' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 5,
                'title' => 'El gallo de oro',
                'open_library_cover_key' => 'OL9174267M',
                'first_publish_year' => 1980,
                'units_available' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 5,
                'title' => 'Juan Rulfo',
                'open_library_cover_key' => 'OL9172875M',
                'first_publish_year' => 1997,
                'units_available' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 6,
                'title' => 'Män som hatar kvinnor',
                'open_library_cover_key' => 'OL16819445M',
                'first_publish_year' => 2005,
                'units_available' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 6,
                'title' => 'Flickan som lekte med elden',
                'open_library_cover_key' => 'OL26377614M',
                'first_publish_year' => 2006,
                'units_available' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 6,
                'title' => 'Luftslottet som sprängdes',
                'open_library_cover_key' => 'OL23991536M',
                'first_publish_year' => 2007,
                'units_available' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 6,
                'title' => 'The Girl with the Dragon Tattoo',
                'open_library_cover_key' => NULL,
                'first_publish_year' => NULL,
                'units_available' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 6,
                'title' => 'The Girl with the Dragon Tattoo',
                'open_library_cover_key' => 'OL31980860M',
                'first_publish_year' => 2008,
                'units_available' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 6,
                'title' => 'The Girl Who Kicked the Hornet\'s Nest',
                'open_library_cover_key' => 'OL24355971M',
                'first_publish_year' => 2009,
                'units_available' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 6,
                'title' => 'The Girl Who Played with Fire',
                'open_library_cover_key' => 'OL31959990M',
                'first_publish_year' => 2009,
                'units_available' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 6,
                'title' => 'The Girl Who Played With Fire',
                'open_library_cover_key' => 'OL28338868M',
                'first_publish_year' => 2009,
                'units_available' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 6,
                'title' => 'Millenium (Män som hatar kvinnor / Flickan som lekte med elden / Luftslottet som sprängdes)',
                'open_library_cover_key' => 'OL26031937M',
                'first_publish_year' => 2010,
                'units_available' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 6,
                'title' => 'Girl With the Dragon Tattoo',
                'open_library_cover_key' => 'OL32237058M',
                'first_publish_year' => 2009,
                'units_available' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 7,
                'title' => 'El túnel',
                'open_library_cover_key' => NULL,
                'first_publish_year' => 1948,
                'units_available' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 7,
                'title' => 'Sobre héroes y tumbas',
                'open_library_cover_key' => 'OL9120991M',
                'first_publish_year' => 1961,
                'units_available' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 7,
                'title' => 'Abaddón el exterminador',
                'open_library_cover_key' => 'OL13234290M',
                'first_publish_year' => 1974,
                'units_available' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 7,
                'title' => 'El escritor y sus fantasmas',
                'open_library_cover_key' => 'OL26449466M',
                'first_publish_year' => 1963,
                'units_available' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 7,
                'title' => 'La resistencia',
                'open_library_cover_key' => 'OL12987887M',
                'first_publish_year' => 2000,
                'units_available' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 7,
                'title' => 'Antes del fin',
                'open_library_cover_key' => 'OL9120988M',
                'first_publish_year' => 1998,
                'units_available' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 7,
                'title' => 'Uno y el universo',
                'open_library_cover_key' => 'OL3841109M',
                'first_publish_year' => 1945,
                'units_available' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 7,
                'title' => 'Tango',
                'open_library_cover_key' => 'OL12952552M',
                'first_publish_year' => 1963,
                'units_available' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 7,
                'title' => 'Hombres y engranajes',
                'open_library_cover_key' => 'OL9860417M',
                'first_publish_year' => 1970,
                'units_available' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 7,
                'title' => 'La cultura en la encrucijada nacional',
                'open_library_cover_key' => 'OL5127855M',
                'first_publish_year' => 1973,
                'units_available' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 8,
                'title' => 'The Murders in the Rue Morgue',
                'open_library_cover_key' => 'OL24475066M',
                'first_publish_year' => 1895,
                'units_available' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 8,
                'title' => 'The Raven',
                'open_library_cover_key' => 'OL6552298M',
                'first_publish_year' => 1845,
                'units_available' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 8,
                'title' => 'The Narrative of Arthur Gordon Pym',
                'open_library_cover_key' => 'OL25389425M',
                'first_publish_year' => 1838,
                'units_available' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 8,
                'title' => 'The Fall of the House of Usher',
                'open_library_cover_key' => 'OL33133952M',
                'first_publish_year' => 1839,
                'units_available' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 8,
                'title' => 'The Black Cat',
                'open_library_cover_key' => 'OL24505174M',
                'first_publish_year' => 1951,
                'units_available' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 8,
                'title' => 'The Masque of the Red Death',
                'open_library_cover_key' => 'OL2026452M',
                'first_publish_year' => 1922,
                'units_available' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 8,
                'title' => 'The Works of Edgar Allan Poe in Five Volumes',
                'open_library_cover_key' => 'OL26609723M',
                'first_publish_year' => 1903,
                'units_available' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 8,
                'title' => 'The Tell-Tale Heart',
                'open_library_cover_key' => 'OL4106724M',
                'first_publish_year' => 1976,
                'units_available' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 8,
                'title' => 'The Dark Descent',
                'open_library_cover_key' => 'OL45828696M',
                'first_publish_year' => 1987,
                'units_available' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 8,
                'title' => 'The Gold-Bug',
                'open_library_cover_key' => 'OL6552321M',
                'first_publish_year' => 1890,
                'units_available' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 9,
                'title' => 'The Body in the Library',
                'open_library_cover_key' => 'OL16159111M',
                'first_publish_year' => 1942,
                'units_available' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 9,
                'title' => 'Five Little Pigs',
                'open_library_cover_key' => 'OL51012141M',
                'first_publish_year' => 1942,
                'units_available' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 9,
                'title' => 'Appointment with Death',
                'open_library_cover_key' => 'OL7257830M',
                'first_publish_year' => 1938,
                'units_available' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 9,
                'title' => 'A Caribbean Mystery',
                'open_library_cover_key' => 'OL51012139M',
                'first_publish_year' => 1964,
                'units_available' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 9,
                'title' => 'The Hollow',
                'open_library_cover_key' => 'OL47237529M',
                'first_publish_year' => 1946,
                'units_available' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 9,
                'title' => 'The Secret of Chimneys',
                'open_library_cover_key' => 'OL40281128M',
                'first_publish_year' => 1925,
                'units_available' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 9,
                'title' => 'Hercule Poirot\'s Christmas',
                'open_library_cover_key' => 'OL39217511M',
                'first_publish_year' => 1939,
                'units_available' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 9,
                'title' => 'The Moving Finger',
                'open_library_cover_key' => 'OL47231963M',
                'first_publish_year' => 1942,
                'units_available' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 9,
                'title' => 'The Big Four',
                'open_library_cover_key' => 'OL40281005M',
                'first_publish_year' => 1927,
                'units_available' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 9,
                'title' => 'The Mirror Crack\'d from Side to Side',
                'open_library_cover_key' => 'OL31883057M',
                'first_publish_year' => 1960,
                'units_available' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 10,
                'title' => 'Carrie',
                'open_library_cover_key' => 'OL27902097M',
                'first_publish_year' => 1974,
                'units_available' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 10,
                'title' => '\'Salem’s Lot',
                'open_library_cover_key' => 'OL5427893M',
                'first_publish_year' => 1975,
                'units_available' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 10,
                'title' => 'Misery',
                'open_library_cover_key' => NULL,
                'first_publish_year' => 1978,
                'units_available' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 10,
                'title' => 'The Shining',
                'open_library_cover_key' => 'OL22312685M',
                'first_publish_year' => 1977,
                'units_available' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 10,
                'title' => 'It',
                'open_library_cover_key' => NULL,
                'first_publish_year' => 1986,
                'units_available' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 10,
                'title' => 'The Gunslinger',
                'open_library_cover_key' => 'OL24944189M',
                'first_publish_year' => 1976,
                'units_available' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 10,
                'title' => 'The Green Mile',
                'open_library_cover_key' => NULL,
                'first_publish_year' => 1996,
                'units_available' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 10,
                'title' => 'Pet Sematary',
                'open_library_cover_key' => 'OL33965435M',
                'first_publish_year' => 1983,
                'units_available' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 10,
                'title' => 'The Dead Zone',
                'open_library_cover_key' => 'OL50998939M',
                'first_publish_year' => 1979,
                'units_available' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 10,
                'title' => 'The Stand',
                'open_library_cover_key' => 'OL25159731M',
                'first_publish_year' => 1978,
                'units_available' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 11,
                'title' => 'Rayuela',
                'open_library_cover_key' => 'OL2980196M',
                'first_publish_year' => 1963,
                'units_available' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 11,
                'title' => 'Final del juego',
                'open_library_cover_key' => 'OL9199407M',
                'first_publish_year' => 1956,
                'units_available' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 11,
                'title' => 'Todos los fuegos el fuego',
                'open_library_cover_key' => NULL,
                'first_publish_year' => 1966,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 11,
                'title' => 'Bestiario',
                'open_library_cover_key' => 'OL18666653M',
                'first_publish_year' => 1951,
                'units_available' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 11,
                'title' => 'Historias de cronopios y de famas',
                'open_library_cover_key' => 'OL9592664M',
                'first_publish_year' => 1962,
                'units_available' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 11,
                'title' => 'Antología de la literatura fantástica',
                'open_library_cover_key' => 'OL24240650M',
                'first_publish_year' => 1940,
                'units_available' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 11,
                'title' => '62/Modelo para armar',
                'open_library_cover_key' => 'OL9134036M',
                'first_publish_year' => 1968,
                'units_available' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 11,
                'title' => 'Prentice Hall Literature--World Masterpieces',
                'open_library_cover_key' => 'OL9298347M',
                'first_publish_year' => 1991,
                'units_available' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 11,
                'title' => 'Los premios',
                'open_library_cover_key' => 'OL3462430M',
                'first_publish_year' => 1960,
                'units_available' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 11,
                'title' => 'Las armas secretas',
                'open_library_cover_key' => 'OL9199406M',
                'first_publish_year' => 1963,
                'units_available' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 12,
                'title' => 'A Game of Thrones',
                'open_library_cover_key' => 'OL7829767M',
                'first_publish_year' => 1996,
                'units_available' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 12,
                'title' => 'A Clash of Kings',
                'open_library_cover_key' => 'OL376045M',
                'first_publish_year' => 1998,
                'units_available' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 12,
                'title' => 'A Feast for Crows',
                'open_library_cover_key' => 'OL23247419M',
                'first_publish_year' => 2005,
                'units_available' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 12,
                'title' => 'A Storm of Swords',
                'open_library_cover_key' => 'OL7255734M',
                'first_publish_year' => 2000,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 12,
                'title' => 'A Dance With Dragons',
                'open_library_cover_key' => 'OL25229207M',
                'first_publish_year' => 2008,
                'units_available' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 12,
                'title' => 'A Knight of the Seven Kingdoms',
                'open_library_cover_key' => 'OL26143783M',
                'first_publish_year' => 2013,
                'units_available' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 12,
                'title' => 'A Song of Ice and Fire (A Game of Thrones / A Clash of Kings / A Storm of Swords / A Feast for Crows / A Dance with Dragons)',
                'open_library_cover_key' => 'OL25936505M',
                'first_publish_year' => 2012,
                'units_available' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 12,
                'title' => 'The World of Ice & Fire',
                'open_library_cover_key' => 'OL27170045M',
                'first_publish_year' => 2014,
                'units_available' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 12,
                'title' => 'Fevre Dream',
                'open_library_cover_key' => 'OL60296795M',
                'first_publish_year' => 1982,
                'units_available' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 12,
                'title' => 'The Ice Dragon',
                'open_library_cover_key' => 'OL8053683M',
                'first_publish_year' => 2006,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 13,
                'title' => 'Harry Potter and the Order of the Phoenix',
                'open_library_cover_key' => 'OL25662116M',
                'first_publish_year' => 2003,
                'units_available' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 13,
                'title' => 'Harry Potter and the Half-Blood Prince',
                'open_library_cover_key' => 'OL24190024M',
                'first_publish_year' => 2005,
                'units_available' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 13,
                'title' => 'Harry Potter and the Goblet of Fire',
                'open_library_cover_key' => 'OL25683482M',
                'first_publish_year' => 1993,
                'units_available' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 13,
                'title' => 'Harry Potter and the Philosopher\'s Stone',
                'open_library_cover_key' => 'OL22856696M',
                'first_publish_year' => 1997,
                'units_available' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 13,
                'title' => 'Harry Potter and the Chamber of Secrets',
                'open_library_cover_key' => 'OL26594474M',
                'first_publish_year' => 1998,
                'units_available' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 13,
                'title' => 'Harry Potter and the Deathly Hallows',
                'open_library_cover_key' => 'OL28172760M',
                'first_publish_year' => 2007,
                'units_available' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 13,
                'title' => 'Harry Potter and the Prisoner of Azkaban',
                'open_library_cover_key' => 'OL26234270M',
                'first_publish_year' => 1999,
                'units_available' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 13,
                'title' => 'The Tales of Beedle the Bard',
                'open_library_cover_key' => NULL,
                'first_publish_year' => 2008,
                'units_available' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 13,
                'title' => 'Fantastic Beasts and Where to Find Them',
                'open_library_cover_key' => 'OL26767687M',
                'first_publish_year' => 2001,
                'units_available' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 13,
                'title' => 'The Casual Vacancy',
                'open_library_cover_key' => NULL,
                'first_publish_year' => 2012,
                'units_available' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 14,
                'title' => 'La dame aux camélias [novel]',
                'open_library_cover_key' => 'OL13721326M',
                'first_publish_year' => 1848,
                'units_available' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 14,
                'title' => 'La dame aux camélias [play]',
                'open_library_cover_key' => 'OL20434885M',
                'first_publish_year' => 1855,
                'units_available' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 14,
                'title' => 'La demi-monde',
                'open_library_cover_key' => 'OL22443042M',
                'first_publish_year' => 1855,
                'units_available' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 14,
                'title' => 'Lady with the Camellias, a New Translation with a New Preface',
                'open_library_cover_key' => NULL,
                'first_publish_year' => 1954,
                'units_available' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 14,
                'title' => 'Camille',
                'open_library_cover_key' => 'OL52332658M',
                'first_publish_year' => 1935,
                'units_available' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 14,
                'title' => 'Dama de Las Camelias',
                'open_library_cover_key' => NULL,
                'first_publish_year' => 2013,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 14,
                'title' => 'Théâtre complet de Al. Dumas Fils',
                'open_library_cover_key' => NULL,
                'first_publish_year' => 1801,
                'units_available' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 14,
                'title' => 'Affaire Clemenceau',
                'open_library_cover_key' => 'OL20525654M',
                'first_publish_year' => 1866,
                'units_available' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 14,
                'title' => 'The Son of Clemenceau',
                'open_library_cover_key' => 'OL32446981M',
                'first_publish_year' => 2005,
                'units_available' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 14,
                'title' => 'La question d\'argent',
                'open_library_cover_key' => 'OL24143707M',
                'first_publish_year' => 1857,
                'units_available' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 15,
                'title' => 'The Old Man and the Sea',
                'open_library_cover_key' => 'OL7893352M',
                'first_publish_year' => 1952,
                'units_available' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 15,
                'title' => 'The Sun Also Rises',
                'open_library_cover_key' => 'OL9274797M',
                'first_publish_year' => 1926,
                'units_available' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 15,
                'title' => 'A Farewell to Arms',
                'open_library_cover_key' => 'OL24206828M',
                'first_publish_year' => 1929,
                'units_available' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 15,
                'title' => 'For Whom the Bell Tolls',
                'open_library_cover_key' => 'OL10602076M',
                'first_publish_year' => 1940,
                'units_available' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 15,
                'title' => 'The Complete Short Stories of Ernest Hemingway',
                'open_library_cover_key' => 'OL22381205M',
                'first_publish_year' => 1930,
                'units_available' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 15,
                'title' => 'To have and have not',
                'open_library_cover_key' => 'OL6803891M',
                'first_publish_year' => 1937,
                'units_available' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 15,
                'title' => 'A Moveable Feast',
                'open_library_cover_key' => NULL,
                'first_publish_year' => 1964,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 15,
                'title' => 'Men Without Women',
                'open_library_cover_key' => 'OL1004232M',
                'first_publish_year' => 1927,
                'units_available' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 15,
                'title' => 'Islands in the Stream',
                'open_library_cover_key' => 'OL7947664M',
                'first_publish_year' => 1752,
                'units_available' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => 15,
                'title' => 'Green Hills of Africa',
                'open_library_cover_key' => 'OL24933769M',
                'first_publish_year' => 1935,
                'units_available' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}